# Generated by Django 4.1.5 on 2023-01-11 09:47

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=42)),
                ("password", models.CharField(max_length=75)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "document",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Document2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "types",
                    models.CharField(
                        choices=[
                            ("producer", "producer"),
                            ("brand owner", "brand owner"),
                            ("importer", "importer"),
                        ],
                        default="producer",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("sales", "sales"), ("procurement", "procurement")],
                        default="sales",
                        max_length=20,
                    ),
                ),
                ("file_name", models.CharField(max_length=50)),
                ("document_excel", app.models.BlobField()),
                ("document_pdf", app.models.BlobField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "document2",
                "managed": True,
            },
        ),
    ]
