# Generated by Django 4.1.5 on 2023-01-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document2",
            name="identity",
            field=models.CharField(default=3, max_length=75),
            preserve_default=False,
        ),
    ]
