# Generated by Django 4.1.5 on 2023-01-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_document2_file_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document2",
            name="file_path",
        ),
    ]
