# Generated by Django 4.1.5 on 2023-01-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_document2_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document2',
            name='document_pdf',
            field=models.FileField(default=4, upload_to=''),
            preserve_default=False,
        ),
    ]
