# Generated by Django 4.1.5 on 2023-01-16 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_document2_document_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document2',
            name='document_pdf',
        ),
    ]
