# Generated by Django 4.1.5 on 2023-01-16 10:51

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_document2_document_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='document2',
            name='document_pdf',
            field=app.models.BlobField(default=4),
            preserve_default=False,
        ),
    ]
