# Generated by Django 4.1.5 on 2023-01-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_document2_document_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='document2',
            name='file_name',
            field=models.CharField(default=5, max_length=75),
            preserve_default=False,
        ),
    ]
